version: "3"
services:
  pychain-node1:
    container_name: "pychain-node1"
    build:
      context: "../"
      dockerfile: "docker/Dockerfile"
      args:
        node_number: "1"
    volumes:
      - ../:/usr/src/app/
      - node1:/usr/src/app/app/conf

    ports:
      - "5001:5001"
    environment:
      FLASK_DEBUG: 1
      FLASK_APP: './entrypoint.py'
    networks:
      - app-net
    tty: true

  pychain-node2:
    container_name: "pychain-node2"
    build:
      context: "../"
      dockerfile: "docker/Dockerfile"
      args:
        node_number: "2"
    volumes:
      - ../:/usr/src/app/
      - node2:/usr/src/app/app/conf


    ports:
      - "5002:5002"
    environment:
      FLASK_DEBUG: 1
      FLASK_APP: './entrypoint.py'
    networks:
      - app-net
    tty: true

  pychain-node3:
    container_name: "pychain-node3"
    build:
      context: "../"
      dockerfile: "docker/Dockerfile"
      args:
        node_number: "3"
    volumes:
      - ../:/usr/src/app/
      - node3:/usr/src/app/app/conf

    ports:
      - "5003:5003"
    environment:
      FLASK_DEBUG: 1
      FLASK_APP: './entrypoint.py'
    networks:
      - app-net
    tty: true

networks:
  app-net:
    driver: bridge

volumes:
  node1: {}
  node2: {}
  node3: {}
