version: "3"
services:
  pychain-node1:
    container_name: "pychain-node1"
    build:
      context: "../"
      dockerfile: "docker/Dockerfile"
      args:
        node_number: "1"
    volumes:
      - ../:/usr/src/app/
      - conf1:/usr/src/app/app/conf
    ports:
      - "5001:5001"
    environment:
      FLASK_DEBUG: 1
      FLASK_APP: './app.py'
    networks:
      - app-net

  pychain-node2:
    container_name: "pychain-node2"
    build:
      context: "../"
      dockerfile: "docker/Dockerfile"
      args:
        node_number: "2"
    volumes:
      - ../:/usr/src/app/
      - conf2:/usr/src/app/app/conf
    ports:
      - "5002:5002"
    environment:
      FLASK_DEBUG: 1
      FLASK_APP: './app.py'
    networks:
      - app-net


  pychain-node3:
    container_name: "pychain-node3"
    build:
      context: "../"
      dockerfile: "docker/Dockerfile"
      args:
        node_number: "3"
    volumes:
      - ../:/usr/src/app/
      - conf3:/usr/src/app/app/conf
    ports:
      - "5003:5003"
    environment:
      FLASK_DEBUG: 1
      FLASK_APP: './app.py'
    networks:
      - app-net

networks:
  app-net:
    driver: bridge

volumes:
  conf1: {}
  conf2: {}
  conf3: {}
