version: "3"
services:
  pychain-node1:
    container_name: "pychain-node1"
    build:
      context: "../"
      dockerfile: "docker/Dockerfile"
      args:
        port: "5000"
    volumes:
      - ../:/usr/src/app/
    ports:
      - "5000:5000"
    environment:
      FLASK_DEBUG: 1
      FLASK_APP: './app.py'
    networks:
      - app-net

  pychain-node2:
    container_name: "pychain-node2"
    build:
      context: "../"
      dockerfile: "docker/Dockerfile"
      args:
        port: "5001"
    volumes:
      - ../:/usr/src/app/
    ports:
      - "5001:5001"
    environment:
      FLASK_DEBUG: 1
      FLASK_APP: './app.py'
    networks:
      - app-net

networks:
  app-net:
    driver: bridge
