"""empty message

Revision ID: cc4801894a1c
Revises: 
Create Date: 2019-01-02 07:58:37.625443

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc4801894a1c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blocks',
    sa.Column('block_id', sa.Text(), autoincrement=False, nullable=False),
    sa.Column('block_number', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=10), nullable=False),
    sa.Column('previous_block_hash', sa.String(length=64), nullable=False),
    sa.Column('timestamp', sa.Integer(), nullable=False),
    sa.Column('merkle_root', sa.String(length=64), nullable=False),
    sa.Column('difficulty_target', sa.Integer(), nullable=False),
    sa.Column('nonce', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('block_id')
    )
    op.create_table('peer_nodes',
    sa.Column('peer_node_id', sa.Text(), autoincrement=False, nullable=False),
    sa.Column('url', sa.String(length=64), nullable=False),
    sa.Column('address', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('peer_node_id')
    )
    op.create_table('transactions',
    sa.Column('transaction_id', sa.Text(), autoincrement=False, nullable=False),
    sa.Column('block_id', sa.Text(), nullable=False),
    sa.Column('locktime', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['block_id'], ['blocks.block_id'], ),
    sa.PrimaryKeyConstraint('transaction_id')
    )
    op.create_table('transaction_outputs',
    sa.Column('transaction_output_id', sa.Text(), autoincrement=False, nullable=False),
    sa.Column('transaction_id', sa.Text(), nullable=True),
    sa.Column('amount', sa.Float(asdecimal=True), nullable=False),
    sa.Column('locking_script', sa.Text(), nullable=False),
    sa.Column('sender_address', sa.Text(), nullable=False),
    sa.Column('recipient_address', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.transaction_id'], ),
    sa.PrimaryKeyConstraint('transaction_output_id')
    )
    op.create_table('transaction_inputs',
    sa.Column('transaction_input_id', sa.Text(), autoincrement=False, nullable=False),
    sa.Column('transaction_id', sa.Text(), nullable=False),
    sa.Column('transaction_output_id', sa.Text(), nullable=False),
    sa.Column('unlocking_script', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.transaction_id'], ),
    sa.ForeignKeyConstraint(['transaction_output_id'], ['transaction_outputs.transaction_output_id'], ),
    sa.PrimaryKeyConstraint('transaction_input_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaction_inputs')
    op.drop_table('transaction_outputs')
    op.drop_table('transactions')
    op.drop_table('peer_nodes')
    op.drop_table('blocks')
    # ### end Alembic commands ###
